// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: rpc_client_stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoundPrepDone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoundPrepDone) Reset() {
	*x = RoundPrepDone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_client_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoundPrepDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundPrepDone) ProtoMessage() {}

func (x *RoundPrepDone) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_client_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundPrepDone.ProtoReflect.Descriptor instead.
func (*RoundPrepDone) Descriptor() ([]byte, []int) {
	return file_rpc_client_stream_proto_rawDescGZIP(), []int{0}
}

type AwkMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Awk:
	//
	//	*AwkMsg_PrepDone
	Awk isAwkMsg_Awk `protobuf_oneof:"awk"`
}

func (x *AwkMsg) Reset() {
	*x = AwkMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_client_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AwkMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwkMsg) ProtoMessage() {}

func (x *AwkMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_client_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwkMsg.ProtoReflect.Descriptor instead.
func (*AwkMsg) Descriptor() ([]byte, []int) {
	return file_rpc_client_stream_proto_rawDescGZIP(), []int{1}
}

func (m *AwkMsg) GetAwk() isAwkMsg_Awk {
	if m != nil {
		return m.Awk
	}
	return nil
}

func (x *AwkMsg) GetPrepDone() *RoundPrepDone {
	if x, ok := x.GetAwk().(*AwkMsg_PrepDone); ok {
		return x.PrepDone
	}
	return nil
}

type isAwkMsg_Awk interface {
	isAwkMsg_Awk()
}

type AwkMsg_PrepDone struct {
	PrepDone *RoundPrepDone `protobuf:"bytes,3,opt,name=prepDone,proto3,oneof"`
}

func (*AwkMsg_PrepDone) isAwkMsg_Awk() {}

var File_rpc_client_stream_proto protoreflect.FileDescriptor

var file_rpc_client_stream_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x70, 0x44, 0x6f, 0x6e,
	0x65, 0x22, 0x43, 0x0a, 0x06, 0x41, 0x77, 0x6b, 0x4d, 0x73, 0x67, 0x12, 0x32, 0x0a, 0x08, 0x70,
	0x72, 0x65, 0x70, 0x44, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x50, 0x72, 0x65, 0x70, 0x44,
	0x6f, 0x6e, 0x65, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x65, 0x70, 0x44, 0x6f, 0x6e, 0x65, 0x42,
	0x05, 0x0a, 0x03, 0x61, 0x77, 0x6b, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x72, 0x69, 0x61, 0x2d, 0x6d, 0x7a, 0x2f, 0x62, 0x61,
	0x73, 0x68, 0x2d, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_client_stream_proto_rawDescOnce sync.Once
	file_rpc_client_stream_proto_rawDescData = file_rpc_client_stream_proto_rawDesc
)

func file_rpc_client_stream_proto_rawDescGZIP() []byte {
	file_rpc_client_stream_proto_rawDescOnce.Do(func() {
		file_rpc_client_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_client_stream_proto_rawDescData)
	})
	return file_rpc_client_stream_proto_rawDescData
}

var file_rpc_client_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_client_stream_proto_goTypes = []interface{}{
	(*RoundPrepDone)(nil), // 0: proto.RoundPrepDone
	(*AwkMsg)(nil),        // 1: proto.AwkMsg
}
var file_rpc_client_stream_proto_depIdxs = []int32{
	0, // 0: proto.AwkMsg.prepDone:type_name -> proto.RoundPrepDone
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_client_stream_proto_init() }
func file_rpc_client_stream_proto_init() {
	if File_rpc_client_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_client_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoundPrepDone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_client_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AwkMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rpc_client_stream_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*AwkMsg_PrepDone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_client_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_client_stream_proto_goTypes,
		DependencyIndexes: file_rpc_client_stream_proto_depIdxs,
		MessageInfos:      file_rpc_client_stream_proto_msgTypes,
	}.Build()
	File_rpc_client_stream_proto = out.File
	file_rpc_client_stream_proto_rawDesc = nil
	file_rpc_client_stream_proto_goTypes = nil
	file_rpc_client_stream_proto_depIdxs = nil
}
