// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: rpc_server_stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerJoined struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *PlayerJoined) Reset() {
	*x = PlayerJoined{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_server_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoined) ProtoMessage() {}

func (x *PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoined.ProtoReflect.Descriptor instead.
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return file_rpc_server_stream_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerJoined) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type PlayerLeft struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *Player `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *PlayerLeft) Reset() {
	*x = PlayerLeft{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_server_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeft) ProtoMessage() {}

func (x *PlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeft.ProtoReflect.Descriptor instead.
func (*PlayerLeft) Descriptor() ([]byte, []int) {
	return file_rpc_server_stream_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerLeft) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type LoadRound struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundNumber int32  `protobuf:"varint,1,opt,name=roundNumber,proto3" json:"roundNumber,omitempty"`
	Question    string `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	InputFile   []byte `protobuf:"bytes,3,opt,name=inputFile,proto3" json:"inputFile,omitempty"`
	OutputFile  []byte `protobuf:"bytes,4,opt,name=outputFile,proto3" json:"outputFile,omitempty"`
}

func (x *LoadRound) Reset() {
	*x = LoadRound{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_server_stream_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRound) ProtoMessage() {}

func (x *LoadRound) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_stream_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRound.ProtoReflect.Descriptor instead.
func (*LoadRound) Descriptor() ([]byte, []int) {
	return file_rpc_server_stream_proto_rawDescGZIP(), []int{2}
}

func (x *LoadRound) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *LoadRound) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *LoadRound) GetInputFile() []byte {
	if x != nil {
		return x.InputFile
	}
	return nil
}

func (x *LoadRound) GetOutputFile() []byte {
	if x != nil {
		return x.OutputFile
	}
	return nil
}

type CountingDown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundNumber int32                  `protobuf:"varint,1,opt,name=roundNumber,proto3" json:"roundNumber,omitempty"`
	StartsAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=startsAt,proto3" json:"startsAt,omitempty"`
}

func (x *CountingDown) Reset() {
	*x = CountingDown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_server_stream_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountingDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountingDown) ProtoMessage() {}

func (x *CountingDown) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_stream_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountingDown.ProtoReflect.Descriptor instead.
func (*CountingDown) Descriptor() ([]byte, []int) {
	return file_rpc_server_stream_proto_rawDescGZIP(), []int{3}
}

func (x *CountingDown) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *CountingDown) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

type RoundStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundNumber int32                  `protobuf:"varint,1,opt,name=roundNumber,proto3" json:"roundNumber,omitempty"`
	EndsAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=endsAt,proto3" json:"endsAt,omitempty"`
}

func (x *RoundStarted) Reset() {
	*x = RoundStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_server_stream_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoundStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundStarted) ProtoMessage() {}

func (x *RoundStarted) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_stream_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundStarted.ProtoReflect.Descriptor instead.
func (*RoundStarted) Descriptor() ([]byte, []int) {
	return file_rpc_server_stream_proto_rawDescGZIP(), []int{4}
}

func (x *RoundStarted) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *RoundStarted) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

type SubmitRoundScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoundNumber int32 `protobuf:"varint,1,opt,name=roundNumber,proto3" json:"roundNumber,omitempty"`
}

func (x *SubmitRoundScore) Reset() {
	*x = SubmitRoundScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_server_stream_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitRoundScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRoundScore) ProtoMessage() {}

func (x *SubmitRoundScore) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_stream_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRoundScore.ProtoReflect.Descriptor instead.
func (*SubmitRoundScore) Descriptor() ([]byte, []int) {
	return file_rpc_server_stream_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitRoundScore) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

type GameOver struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameOver) Reset() {
	*x = GameOver{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_server_stream_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOver) ProtoMessage() {}

func (x *GameOver) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_stream_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOver.ProtoReflect.Descriptor instead.
func (*GameOver) Descriptor() ([]byte, []int) {
	return file_rpc_server_stream_proto_rawDescGZIP(), []int{6}
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*Event_PlayerJoined
	//	*Event_PlayerLeft
	//	*Event_LoadRound
	//	*Event_CountingDown
	//	*Event_RoundStarted
	//	*Event_SubmitRoundScore
	//	*Event_GameOver
	Event isEvent_Event `protobuf_oneof:"event"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_server_stream_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_server_stream_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_rpc_server_stream_proto_rawDescGZIP(), []int{7}
}

func (m *Event) GetEvent() isEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *Event) GetPlayerJoined() *PlayerJoined {
	if x, ok := x.GetEvent().(*Event_PlayerJoined); ok {
		return x.PlayerJoined
	}
	return nil
}

func (x *Event) GetPlayerLeft() *PlayerLeft {
	if x, ok := x.GetEvent().(*Event_PlayerLeft); ok {
		return x.PlayerLeft
	}
	return nil
}

func (x *Event) GetLoadRound() *LoadRound {
	if x, ok := x.GetEvent().(*Event_LoadRound); ok {
		return x.LoadRound
	}
	return nil
}

func (x *Event) GetCountingDown() *CountingDown {
	if x, ok := x.GetEvent().(*Event_CountingDown); ok {
		return x.CountingDown
	}
	return nil
}

func (x *Event) GetRoundStarted() *RoundStarted {
	if x, ok := x.GetEvent().(*Event_RoundStarted); ok {
		return x.RoundStarted
	}
	return nil
}

func (x *Event) GetSubmitRoundScore() *SubmitRoundScore {
	if x, ok := x.GetEvent().(*Event_SubmitRoundScore); ok {
		return x.SubmitRoundScore
	}
	return nil
}

func (x *Event) GetGameOver() *GameOver {
	if x, ok := x.GetEvent().(*Event_GameOver); ok {
		return x.GameOver
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_PlayerJoined struct {
	PlayerJoined *PlayerJoined `protobuf:"bytes,1,opt,name=playerJoined,proto3,oneof"`
}

type Event_PlayerLeft struct {
	PlayerLeft *PlayerLeft `protobuf:"bytes,2,opt,name=playerLeft,proto3,oneof"`
}

type Event_LoadRound struct {
	LoadRound *LoadRound `protobuf:"bytes,3,opt,name=loadRound,proto3,oneof"`
}

type Event_CountingDown struct {
	CountingDown *CountingDown `protobuf:"bytes,4,opt,name=countingDown,proto3,oneof"`
}

type Event_RoundStarted struct {
	RoundStarted *RoundStarted `protobuf:"bytes,5,opt,name=roundStarted,proto3,oneof"`
}

type Event_SubmitRoundScore struct {
	SubmitRoundScore *SubmitRoundScore `protobuf:"bytes,6,opt,name=submitRoundScore,proto3,oneof"`
}

type Event_GameOver struct {
	GameOver *GameOver `protobuf:"bytes,7,opt,name=gameOver,proto3,oneof"`
}

func (*Event_PlayerJoined) isEvent_Event() {}

func (*Event_PlayerLeft) isEvent_Event() {}

func (*Event_LoadRound) isEvent_Event() {}

func (*Event_CountingDown) isEvent_Event() {}

func (*Event_RoundStarted) isEvent_Event() {}

func (*Event_SubmitRoundScore) isEvent_Event() {}

func (*Event_GameOver) isEvent_Event() {}

var File_rpc_server_stream_proto protoreflect.FileDescriptor

var file_rpc_server_stream_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a,
	0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x25, 0x0a,
	0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65,
	0x66, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x87, 0x01, 0x0a, 0x09, 0x4c, 0x6f,
	0x61, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46, 0x69,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x22, 0x68, 0x0a, 0x0c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x44,
	0x6f, 0x77, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x73, 0x41,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x73, 0x41, 0x74, 0x22, 0x64, 0x0a,
	0x0c, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0b, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x32, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x73, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x65, 0x6e, 0x64,
	0x73, 0x41, 0x74, 0x22, 0x34, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x0a, 0x0a, 0x08, 0x47, 0x61, 0x6d,
	0x65, 0x4f, 0x76, 0x65, 0x72, 0x22, 0x9e, 0x03, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x39, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x12, 0x33, 0x0a, 0x0a, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x66,
	0x74, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c, 0x65, 0x66, 0x74, 0x12,
	0x30, 0x0a, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x12, 0x39, 0x0a, 0x0c, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x6f, 0x77,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x6f, 0x77, 0x6e, 0x48, 0x00, 0x52, 0x0c,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x69, 0x6e, 0x67, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x39, 0x0a, 0x0c,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x45, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x48, 0x00, 0x52, 0x10, 0x73, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x2d,
	0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4f, 0x76, 0x65, 0x72, 0x42, 0x07, 0x0a,
	0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x72, 0x69, 0x61, 0x2d, 0x6d, 0x7a, 0x2f, 0x62, 0x61,
	0x73, 0x68, 0x2d, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_server_stream_proto_rawDescOnce sync.Once
	file_rpc_server_stream_proto_rawDescData = file_rpc_server_stream_proto_rawDesc
)

func file_rpc_server_stream_proto_rawDescGZIP() []byte {
	file_rpc_server_stream_proto_rawDescOnce.Do(func() {
		file_rpc_server_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_server_stream_proto_rawDescData)
	})
	return file_rpc_server_stream_proto_rawDescData
}

var file_rpc_server_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rpc_server_stream_proto_goTypes = []interface{}{
	(*PlayerJoined)(nil),          // 0: proto.PlayerJoined
	(*PlayerLeft)(nil),            // 1: proto.PlayerLeft
	(*LoadRound)(nil),             // 2: proto.LoadRound
	(*CountingDown)(nil),          // 3: proto.CountingDown
	(*RoundStarted)(nil),          // 4: proto.RoundStarted
	(*SubmitRoundScore)(nil),      // 5: proto.SubmitRoundScore
	(*GameOver)(nil),              // 6: proto.GameOver
	(*Event)(nil),                 // 7: proto.Event
	(*Player)(nil),                // 8: proto.Player
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_rpc_server_stream_proto_depIdxs = []int32{
	8,  // 0: proto.PlayerJoined.player:type_name -> proto.Player
	8,  // 1: proto.PlayerLeft.player:type_name -> proto.Player
	9,  // 2: proto.CountingDown.startsAt:type_name -> google.protobuf.Timestamp
	9,  // 3: proto.RoundStarted.endsAt:type_name -> google.protobuf.Timestamp
	0,  // 4: proto.Event.playerJoined:type_name -> proto.PlayerJoined
	1,  // 5: proto.Event.playerLeft:type_name -> proto.PlayerLeft
	2,  // 6: proto.Event.loadRound:type_name -> proto.LoadRound
	3,  // 7: proto.Event.countingDown:type_name -> proto.CountingDown
	4,  // 8: proto.Event.roundStarted:type_name -> proto.RoundStarted
	5,  // 9: proto.Event.submitRoundScore:type_name -> proto.SubmitRoundScore
	6,  // 10: proto.Event.gameOver:type_name -> proto.GameOver
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_rpc_server_stream_proto_init() }
func file_rpc_server_stream_proto_init() {
	if File_rpc_server_stream_proto != nil {
		return
	}
	file_game_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_server_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerJoined); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_server_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerLeft); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_server_stream_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadRound); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_server_stream_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountingDown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_server_stream_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoundStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_server_stream_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitRoundScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_server_stream_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameOver); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_server_stream_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rpc_server_stream_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*Event_PlayerJoined)(nil),
		(*Event_PlayerLeft)(nil),
		(*Event_LoadRound)(nil),
		(*Event_CountingDown)(nil),
		(*Event_RoundStarted)(nil),
		(*Event_SubmitRoundScore)(nil),
		(*Event_GameOver)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_server_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_server_stream_proto_goTypes,
		DependencyIndexes: file_rpc_server_stream_proto_depIdxs,
		MessageInfos:      file_rpc_server_stream_proto_msgTypes,
	}.Build()
	File_rpc_server_stream_proto = out.File
	file_rpc_server_stream_proto_rawDesc = nil
	file_rpc_server_stream_proto_goTypes = nil
	file_rpc_server_stream_proto_depIdxs = nil
}
